### PR TITLE
add docker-publish.yml

### PR DESCRIPTION
**Pull request by Sporesirius**
Build and publish docker image to ghcr.io (Github Packages).

### CODE REVIEW

**Review by seg6 — APPROVED** [review]

**Comment by seg6** [comment]
Hello, thank you for your contribution. I am not super familiar with Docker, so let's wait for @markus-wa to review the PR as well.

**Comment by markus-wa** [comment]
thanks @Sporesirius :slightly_smiling_face:

**Comment by markus-wa** [comment]
do you know how to fix this 403 error @Sporesirius ? https://github.com/saiko-tech/mmproxy-rs/actions/runs/5049654565/jobs/9059379254

**Comment by Sporesirius** [comment]
@markus-wa Hm, I didn't get that error, maybe a permissions problem?
These are the settings on the forked repo, I have not changed anything.
Or is Github Packages disabled?
image

**Comment by markus-wa** [comment]
I had to change a few org settings - seems to work now `docker run ghcr.io/saiko-tech/mmproxy-rs:main --help`

**Pull request merged**
